"""add_subscription_tables

Revision ID: 03f350fa8cb0
Revises: a7d1e2f3b4c5
Create Date: 2026-05-23 16:43:21.259983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '03f350fa8cb0'
down_revision: Union[str, None] = 'a7d1e2f3b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_configs',
    sa.Column('device_id', sa.String(length=256), nullable=False),
    sa.Column('block_non_contacts', sa.Boolean(), nullable=False),
    sa.Column('allowed_prefixes', sa.JSON(), nullable=False),
    sa.Column('blocked_prefixes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('external_reference', sa.String(length=256), nullable=True),
    sa.Column('preference_id', sa.String(length=256), nullable=True),
    sa.Column('payment_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('renewal_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=256), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_prefixes_prefix'), table_name='area_prefixes')
    op.drop_index(op.f('ix_blacklist_entries_user_phone'), table_name='blacklist_entries')
    op.drop_index(op.f('idx_phone_numbers_e164'), table_name='phone_numbers')
    op.drop_index(op.f('idx_phone_numbers_status_non_clean'), table_name='phone_numbers', postgresql_where="(status <> 'CLEAN'::numberstatus)")
    op.drop_index(op.f('idx_reports_phone_created'), table_name='reports')
    op.drop_index(op.f('ix_whitelist_entries_user_phone'), table_name='whitelist_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_whitelist_entries_user_phone'), 'whitelist_entries', ['user_id', 'phone_hash'], unique=True)
    op.create_index(op.f('idx_reports_phone_created'), 'reports', ['phone_number_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_phone_numbers_status_non_clean'), 'phone_numbers', ['status'], unique=False, postgresql_where="(status <> 'CLEAN'::numberstatus)")
    op.create_index(op.f('idx_phone_numbers_e164'), 'phone_numbers', ['number_e164'], unique=False)
    op.create_index(op.f('ix_blacklist_entries_user_phone'), 'blacklist_entries', ['user_id', 'phone_hash'], unique=True)
    op.create_index(op.f('idx_prefixes_prefix'), 'area_prefixes', ['prefix'], unique=False)
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('device_configs')
    # ### end Alembic commands ###
