"""add_feedback_events

Revision ID: 4c3b3f82fc0f
Revises: f94ba9b50d68
Create Date: 2026-04-30 10:58:53.026415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4c3b3f82fc0f'
down_revision: Union[str, None] = 'f94ba9b50d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number_id', sa.UUID(), nullable=False),
    sa.Column('reporter_device_id', sa.String(length=64), nullable=False),
    sa.Column('feedback_type', sa.Enum('FALSE_POSITIVE', 'WAS_SPAM', 'CORRECT_BLOCK', 'CORRECT_ALLOW', name='feedbacktype'), nullable=False),
    sa.Column('related_verdict', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback_events')
    # ### end Alembic commands ###
