"""refactor_to_bigint_and_predictive_columns

Revision ID: 6e25a3c014b6
Revises: 03f350fa8cb0
Create Date: 2026-06-13 13:37:44.214338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


"""refactor_to_bigint_and_predictive_columns

Revision ID: 6e25a3c014b6
Revises: 03f350fa8cb0
Create Date: 2026-06-13 13:37:44.214338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e25a3c014b6'
down_revision: Union[str, None] = '03f350fa8cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE feedback_events, reports, phone_numbers CASCADE")
    op.create_table('blocked_calls_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('intercepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_calls_log_phone_number'), 'blocked_calls_log', ['phone_number'], unique=False)

    # Drop child foreign keys first
    op.drop_constraint('feedback_events_phone_number_id_fkey', 'feedback_events', type_='foreignkey')
    op.drop_constraint('reports_phone_number_id_fkey', 'reports', type_='foreignkey')

    # Drop primary key of phone_numbers
    op.drop_constraint('phone_numbers_pkey', 'phone_numbers', type_='primary')
    op.drop_constraint('phone_numbers_number_e164_key', 'phone_numbers', type_='unique')

    # Drop columns
    op.drop_column('phone_numbers', 'number_local')
    op.drop_column('phone_numbers', 'id')
    op.drop_column('phone_numbers', 'number_e164')

    # Add new columns to phone_numbers
    op.add_column('phone_numbers', sa.Column('phone_number', sa.BigInteger(), nullable=False))
    op.add_column('phone_numbers', sa.Column('is_predicted', sa.Boolean(), server_default='false', nullable=False))

    # Set new primary key
    op.create_primary_key('phone_numbers_pkey', 'phone_numbers', ['phone_number'])

    # Add columns and foreign keys to feedback_events
    op.add_column('feedback_events', sa.Column('phone_number', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'feedback_events', 'phone_numbers', ['phone_number'], ['phone_number'])
    op.drop_column('feedback_events', 'phone_number_id')

    # Add columns and foreign keys to reports
    op.add_column('reports', sa.Column('phone_number', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'reports', 'phone_numbers', ['phone_number'], ['phone_number'])
    op.drop_column('reports', 'phone_number_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('phone_number_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'phone_number')

    op.add_column('feedback_events', sa.Column('phone_number_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback_events', type_='foreignkey')
    op.drop_column('feedback_events', 'phone_number')

    op.drop_constraint('phone_numbers_pkey', 'phone_numbers', type_='primary')
    op.drop_column('phone_numbers', 'is_predicted')
    op.drop_column('phone_numbers', 'phone_number')

    op.add_column('phone_numbers', sa.Column('number_e164', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('phone_numbers', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('phone_numbers', sa.Column('number_local', sa.VARCHAR(length=15), autoincrement=False, nullable=False))

    op.create_primary_key('phone_numbers_pkey', 'phone_numbers', ['id'])
    op.create_unique_constraint('phone_numbers_number_e164_key', 'phone_numbers', ['number_e164'])

    op.create_foreign_key('feedback_events_phone_number_id_fkey', 'feedback_events', 'phone_numbers', ['phone_number_id'], ['id'])
    op.create_foreign_key('reports_phone_number_id_fkey', 'reports', 'phone_numbers', ['phone_number_id'], ['id'])
    
    op.alter_column('reports', 'phone_number_id', nullable=False)
    op.alter_column('feedback_events', 'phone_number_id', nullable=False)

    op.drop_index(op.f('ix_blocked_calls_log_phone_number'), table_name='blocked_calls_log')
    op.drop_table('blocked_calls_log')
    # ### end Alembic commands ###
