"""add_import_count_to_phone_number

Revision ID: f28faf7e6678
Revises: 6e25a3c014b6
Create Date: 2026-06-20 09:55:41.795651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f28faf7e6678'
down_revision: Union[str, None] = '6e25a3c014b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_numbers', sa.Column('import_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'import_count')
    # ### end Alembic commands ###
