"""initial_schema

Revision ID: f94ba9b50d68
Revises: 
Create Date: 2026-04-29 13:46:28.798658

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'f94ba9b50d68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_prefixes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=6), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=True),
    sa.Column('is_mobile', sa.Boolean(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('phone_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number_e164', sa.String(length=20), nullable=False),
    sa.Column('number_local', sa.String(length=15), nullable=False),
    sa.Column('prefix_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CLEAN', 'SUSPECT', 'SPAM', 'UNVERIFIED', name='numberstatus'), nullable=False),
    sa.Column('spam_score', sa.SmallInteger(), nullable=False),
    sa.Column('report_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ENACOM', 'CROWDSOURCE', 'AI_AGENT', 'MANUAL', 'SEED', name='numbersource'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('spam_score >= 0 AND spam_score <= 100', name='ck_phone_numbers_spam_score'),
    sa.ForeignKeyConstraint(['prefix_id'], ['area_prefixes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number_e164')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number_id', sa.UUID(), nullable=False),
    sa.Column('reporter_device_id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.Enum('SPAM_CALL', 'ROBOCALL', 'SCAM', 'FRAUD', 'OTHER', name='reporttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_duration_sec', sa.Integer(), nullable=True),
    sa.Column('call_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index("idx_prefixes_prefix", "area_prefixes", ["prefix"])
    op.create_index("idx_phone_numbers_e164", "phone_numbers", ["number_e164"])
    op.create_index(
        "idx_phone_numbers_status_non_clean",
        "phone_numbers",
        ["status"],
        postgresql_where=sa.text("status <> 'CLEAN'"),
    )
    op.create_index(
        "idx_reports_phone_created", "reports", ["phone_number_id", sa.text("created_at DESC")]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_reports_phone_created", table_name="reports")
    op.drop_index("idx_phone_numbers_status_non_clean", table_name="phone_numbers")
    op.drop_index("idx_phone_numbers_e164", table_name="phone_numbers")
    op.drop_index("idx_prefixes_prefix", table_name="area_prefixes")
    op.drop_table("reports")
    op.drop_table("phone_numbers")
    op.drop_table("area_prefixes")
    # ### end Alembic commands ###
